/*

	Historical Spawn Dates
	by Gedemon (2013-2017)

*/

-------------------------------------------------------------------------------
-- Historical Spawn Eras
-- 0 - Ancient Era
-- 1 - Classical Era
-- 2 - Medieval Era
-- 3 - Renaissance Era
-- 4 - Industrial Era
-- 5 - Modern Era
-- 6 - Atomic Era
-- 7 - Digital Era
-- 8 - Future Era
-------------------------------------------------------------------------------
INSERT OR REPLACE INTO HistoricalSpawnEras
(	Civilization,				Era) 
VALUES
-- Major Civilizations
(	'CIVILIZATION_AMERICA',				4 ),
(	'CIVILIZATION_ARABIA',				1 ),
(	'CIVILIZATION_AUSTRALIA',			4 ),
(	'CIVILIZATION_AZTEC',				1 ),
(	'CIVILIZATION_BABYLON_STK',			0 ),
(	'CIVILIZATION_BRAZIL',				4 ),
(	'CIVILIZATION_BYZANTIUM',			2 ),
(	'CIVILIZATION_CANADA',		 	 	4 ),
(	'CIVILIZATION_CHINA',				0 ),
(	'CIVILIZATION_CREE',				2 ),
(	'CIVILIZATION_ENGLAND',				2 ),
(	'CIVILIZATION_EGYPT',				0 ),
(	'CIVILIZATION_ETHIOPIA',			1 ),
(	'CIVILIZATION_FRANCE',				2 ),
(	'CIVILIZATION_GAUL',				0 ),
(	'CIVILIZATION_GEORGIA',				1 ),
(	'CIVILIZATION_GERMANY',				2 ),
(	'CIVILIZATION_GRAN_COLOMBIA',		4 ),
(	'CIVILIZATION_GREECE',				1 ),
(	'CIVILIZATION_HUNGARY',				2 ),
(	'CIVILIZATION_INCA',				1 ),
(	'CIVILIZATION_INDIA',				0 ),
(	'CIVILIZATION_INDONESIA',			2 ),
(	'CIVILIZATION_JAPAN',				2 ),
(	'CIVILIZATION_KHMER',				2 ),
(	'CIVILIZATION_KONGO',				2 ),
(	'CIVILIZATION_KOREA',				1 ),
(	'CIVILIZATION_MAPUCHE',				2 ),
(	'CIVILIZATION_MACEDON',				1 ),
(	'CIVILIZATION_MALI',				2 ),
(	'CIVILIZATION_MAORI',		 		1 ),
(	'CIVILIZATION_MAYA',		 		1 ),
(	'CIVILIZATION_MONGOLIA',			1 ),
(	'CIVILIZATION_NETHERLANDS',			2 ),
(	'CIVILIZATION_NORWAY',				1 ),
(	'CIVILIZATION_NUBIA',				1 ),
(	'CIVILIZATION_OTTOMAN',				3 ),
(	'CIVILIZATION_PERSIA',				0 ),
(	'CIVILIZATION_PHOENICIA',			1 ),
(	'CIVILIZATION_POLAND',				2 ),
(	'CIVILIZATION_ROME',				1 ),
(	'CIVILIZATION_RUSSIA',				2 ),
(	'CIVILIZATION_SCOTLAND',			2 ),
(	'CIVILIZATION_SCYTHIA',				1 ),
(	'CIVILIZATION_SPAIN',				2 ),
(	'CIVILIZATION_SUMERIA',				0 ),
(	'CIVILIZATION_SWEDEN',				2 ),
(	'CIVILIZATION_VIETNAM',				1 ),
(	'CIVILIZATION_ZULU',				3 ),
-- Minor Civilizations
(	'CIVILIZATION_AKKAD',				0 ),
(	'CIVILIZATION_AMSTERDAM',			2 ),
(	'CIVILIZATION_ANTANANARIVO',		3 ),
(	'CIVILIZATION_ANTIOCH',				1 ),
(	'CIVILIZATION_ARMAGH',				2 ),
(	'CIVILIZATION_AUCKLAND',			3 ),
(	'CIVILIZATION_BABYLON',				0 ),
(	'CIVILIZATION_BOLOGNA',		 		2 ),
(	'CIVILIZATION_BRUSSELS',			2 ),
(	'CIVILIZATION_BUENOS_AIRES',		4 ),
(	'CIVILIZATION_CAGUANA',				2 ),
(	'CIVILIZATION_CAHOKIA',				2 ),
(	'CIVILIZATION_CARDIFF',		 		1 ),
(	'CIVILIZATION_FEZ',		  			2 ),
(	'CIVILIZATION_GENEVA',				1 ),
(	'CIVILIZATION_GRANADA',				2 ),
(	'CIVILIZATION_HATTUSA',				0 ),
(	'CIVILIZATION_HUNZA',				1 ),
(	'CIVILIZATION_HONG_KONG',			2 ),
(	'CIVILIZATION_JAKARTA',				2 ),
(	'CIVILIZATION_JERUSALEM',			0 ),
(	'CIVILIZATION_KABUL',				0 ),
(	'CIVILIZATION_KANDY',				2 ),
(	'CIVILIZATION_KUMASI',				2 ),
(	'CIVILIZATION_LAHORE',				0 ),
(	'CIVILIZATION_LA_VENTA',			1 ),
(	'CIVILIZATION_LHASA',				1 ),
(	'CIVILIZATION_LISBON',				2 ),
(	'CIVILIZATION_MEXICO_CITY',			1 ),
(	'CIVILIZATION_MOHENJO_DARO',		0 ),
(	'CIVILIZATION_MUSCAT',				0 ),
(	'CIVILIZATION_NAN_MADOL',			1 ),
(	'CIVILIZATION_NAZCA',		 		0 ),
(	'CIVILIZATION_NGAZARGAMU',			2 ),
(	'CIVILIZATION_PALENQUE',			1 ),
(	'CIVILIZATION_PRESLAV',				1 ),
(	'CIVILIZATION_RAPA_NUI',			2 ),
(	'CIVILIZATION_SEOUL',				1 ),
(	'CIVILIZATION_SINGAPORE',			2 ),
(	'CIVILIZATION_STOCKHOLM',			1 ),
(	'CIVILIZATION_TARUGA',				1 ),
(	'CIVILIZATION_TORONTO',				4 ),
(	'CIVILIZATION_VALLETTA',			1 ),
(	'CIVILIZATION_VATICAN_CITY',		1 ),
(	'CIVILIZATION_VILNIUS',				2 ),
(	'CIVILIZATION_YEREVAN',				0 ),
(	'CIVILIZATION_ZANZIBAR',			2 ),
--Babylon DLC City States
(	'CIVILIZATION_AYUTTHAYA',		 	2	),	
(	'CIVILIZATION_CHINGUETTI',		 	1	),	
(	'CIVILIZATION_JOHANNESBURG',		3	),
(	'CIVILIZATION_NALANDA',		 		0	),
(	'CIVILIZATION_SAMARKAND',		 	0	),
(	'CIVILIZATION_WOLIN',		 		2	),
(	'END_OF_INSERT',				NULL	);	
-- Remove "END_OF_INSERT" entry 
DELETE from HistoricalSpawnEras WHERE Civilization ='END_OF_INSERT';

--End